/*
 * WARNING: There is nothing in this file for students to edit or change.
 *          This file is intended to have no student-serviceable code.
 *
 * "Draw" your GUI using the "Design" tab, and remember to give
 * them memorable variable names in the "Properties" panel
 * as well as make them public variables.
 * 
 * For convenience, you may want to set the default visibility of 
 * GUI elements to be public by going to:
 *    The NetBeans Preferences or Settings menu -> Miscellaneous -> GUI Builder
 * Then set Variables Modifier to public.
 */
package cs20viewcontroller;

import java.awt.Color;
import cs20models.AllModelsForView;
import javax.swing.JScrollPane;
import javax.swing.UIManager;

/**
 * WARNING: Do NOT modify or write any code in this file!
 *
 * @author cheng
 */
public class DrawnView extends AllModelsForView {
    // WARNING: Do NOT modify or write any code in this file!
    // <editor-fold defaultstate="collapsed" desc="Generated Code">

    public DrawnView() {
        initComponents();
    }// </editor-fold>
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        soundGroup = new javax.swing.ButtonGroup();
        volumeTextField = new javax.swing.JTextField();
        volumeLabel = new javax.swing.JLabel();
        startButton = new javax.swing.JButton();
        maxLabel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        resetButton = new javax.swing.JButton();
        maxTimeC = new javax.swing.JTextField();
        maxTimeR = new javax.swing.JTextField();
        applyButton = new javax.swing.JButton();
        timeLabelUNCHANGING = new javax.swing.JLabel();
        maxLabelUNCHANGING = new javax.swing.JLabel();
        timeLabel = new javax.swing.JLabel();
        phaseLabel = new javax.swing.JLabel();
        defaultButton = new javax.swing.JButton();
        dateLabel = new javax.swing.JLabel();
        soundButton1 = new javax.swing.JRadioButton();
        soundButton2 = new javax.swing.JRadioButton();
        soundButton3 = new javax.swing.JRadioButton();
        soundButton4 = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        //colour of precentage counter on red background
        progressBar = new javax.swing.JProgressBar();
        jScrollPane2 = new javax.swing.JScrollPane();
        textArea = new javax.swing.JTextArea();

        soundGroup.add(soundButton1);
        soundGroup.add(soundButton2);
        soundGroup.add(soundButton3);
        soundGroup.add(soundButton4);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Timer");
        setBackground(new java.awt.Color(0, 0, 240));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        setForeground(java.awt.Color.green);
        addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                formPropertyChange(evt);
            }
        });

        volumeTextField.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        volumeTextField.setText("75");
        volumeTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volumeTextFieldActionPerformed(evt);
            }
        });

        volumeLabel.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 11)); // NOI18N
        volumeLabel.setText("Volume:");

        startButton.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 11)); // NOI18N
        startButton.setForeground(new java.awt.Color(102, 0, 153));
        startButton.setText("Start/Stop");
        startButton.setBackground(Color.red);
        startButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startButtonActionPerformed(evt);
            }
        });

        maxLabel.setBackground(new java.awt.Color(51, 153, 255));
        maxLabel.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        maxLabel.setForeground(new java.awt.Color(51, 153, 255));
        maxLabel.setText("20:00");

        jLabel3.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 11)); // NOI18N
        jLabel3.setText("Set Maximum Time In Minutes (Computer Phase):");

        jLabel8.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 11)); // NOI18N
        jLabel8.setText("Set Maximum Time In Seconds (Rest Phase):");

        resetButton.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 11)); // NOI18N
        resetButton.setForeground(new java.awt.Color(102, 0, 153));
        resetButton.setText("Reset");
        resetButton.setBackground(Color.cyan);

        maxTimeC.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        maxTimeC.setText("20");

        maxTimeR.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        maxTimeR.setText("20");

        applyButton.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 11)); // NOI18N
        applyButton.setText("Apply");
        applyButton.setBackground(Color.ORANGE);
        applyButton.setForeground(Color.WHITE);

        timeLabelUNCHANGING.setFont(new java.awt.Font("Yu Gothic UI", 0, 11)); // NOI18N
        timeLabelUNCHANGING.setText("Time (in min:sec):");
        timeLabelUNCHANGING.setForeground(new java.awt.Color(51, 204, 255));

        maxLabelUNCHANGING.setFont(new java.awt.Font("Yu Gothic UI", 0, 11)); // NOI18N
        maxLabelUNCHANGING.setText("Max (in min:sec):");
        maxLabelUNCHANGING.setForeground(new java.awt.Color(51, 153, 255));

        timeLabel.setBackground(new java.awt.Color(0, 0, 0));
        timeLabel.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        timeLabel.setForeground(new java.awt.Color(51, 204, 255));
        timeLabel.setText("00:00");

        phaseLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 11)); // NOI18N
        phaseLabel.setText("Computer Phase: You can be on your device!");

        defaultButton.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 11)); // NOI18N
        defaultButton.setText("Default");
        defaultButton.setBackground(Color.pink);
        defaultButton.setForeground(Color.RED);

        dateLabel.setFont(new java.awt.Font("Yu Gothic", 1, 11)); // NOI18N
        dateLabel.setForeground(new java.awt.Color(255, 255, 255));
        dateLabel.setBackground(Color.BLACK);
        dateLabel.setForeground(Color.WHITE);

        soundButton1.setText("Alarm Type 1");
        soundButton1.setSelected(true);

        soundButton2.setText("Alarm Type 2");

        soundButton3.setText("Alarm Type 3");
        soundButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                soundButton3ActionPerformed(evt);
            }
        });

        soundButton4.setText("Alarm Type 4");

        jTextArea1.setEditable(false);
        jTextArea1.setBackground(new java.awt.Color(240, 50, 50));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Sitka Small", 1, 13)); // NOI18N
        jTextArea1.setForeground(new java.awt.Color(0, 0, 0));
        jTextArea1.setRows(5);
        jTextArea1.setText("Caution: Alarms ring at different \nvolumes, with the order as \n1 < 4 < 3 < 2\n3 and 2 are LOUD! It is recommended\nto reduce the volume when in use.");
        jScrollPane1.setViewportView(jTextArea1);

        progressBar.setBackground(new java.awt.Color(0, 0, 100));
        progressBar.setStringPainted(true);
        progressBar.setString("");
        progressBar.setForeground(new java.awt.Color(0, 0, 255));
        progressBar.setMaximum(aTimerModel.getMaxTimeC() * 60);

        textArea.setBackground(new java.awt.Color(0, 0, 0));
        textArea.setColumns(20);
        textArea.setForeground(new java.awt.Color(100, 0, 100));
        textArea.setRows(5);
        textArea.setText("Records:");
        jScrollPane2.setViewportView(textArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(progressBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(phaseLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(dateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(startButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(resetButton, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(defaultButton)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(applyButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(33, 33, 33)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel8)
                                            .addComponent(volumeLabel)))
                                    .addComponent(jLabel3))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(maxTimeR, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(volumeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(soundButton4)
                                            .addComponent(soundButton3)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(maxTimeC, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(19, 19, 19)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(soundButton1)
                                            .addComponent(soundButton2)))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(timeLabelUNCHANGING)
                                    .addComponent(maxLabelUNCHANGING))
                                .addGap(26, 26, 26)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(timeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(maxLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(progressBar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(maxLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(maxLabelUNCHANGING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(timeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(timeLabelUNCHANGING)))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(soundButton1)
                        .addGap(13, 13, 13)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(maxTimeC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(soundButton2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(maxTimeR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(soundButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(volumeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(soundButton4))
                            .addComponent(volumeLabel))
                        .addGap(8, 8, 8)
                        .addComponent(phaseLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jScrollPane2)))
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(defaultButton)
                            .addComponent(applyButton)
                            .addComponent(startButton)
                            .addComponent(resetButton))
                        .addGap(17, 17, 17))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(dateLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(9, 9, 9))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void volumeTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volumeTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_volumeTextFieldActionPerformed

    private void startButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_startButtonActionPerformed

    private void formPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_formPropertyChange
            // TODO add your handling code here:
    }//GEN-LAST:event_formPropertyChange

    private void soundButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_soundButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_soundButton3ActionPerformed
    // WARNING: Do NOT modify or write any code in this file!
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton applyButton;
    public javax.swing.JLabel dateLabel;
    public javax.swing.JButton defaultButton;
    public javax.swing.JLabel jLabel3;
    public javax.swing.JLabel jLabel8;
    public javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JTextArea jTextArea1;
    public javax.swing.JLabel maxLabel;
    public javax.swing.JLabel maxLabelUNCHANGING;
    public javax.swing.JTextField maxTimeC;
    public javax.swing.JTextField maxTimeR;
    public javax.swing.JLabel phaseLabel;
    public javax.swing.JProgressBar progressBar;
    public javax.swing.JButton resetButton;
    public javax.swing.JRadioButton soundButton1;
    public javax.swing.JRadioButton soundButton2;
    public javax.swing.JRadioButton soundButton3;
    public javax.swing.JRadioButton soundButton4;
    public javax.swing.ButtonGroup soundGroup;
    public javax.swing.JButton startButton;
    public javax.swing.JTextArea textArea;
    public javax.swing.JLabel timeLabel;
    public javax.swing.JLabel timeLabelUNCHANGING;
    public javax.swing.JLabel volumeLabel;
    public javax.swing.JTextField volumeTextField;
    // End of variables declaration//GEN-END:variables
}
